main/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("portfolio/", views.portfolio, name="portfolio"),

    path("session/wedding", views.weddingSession, name="weddingSession"),
    path("session/newborn", views.newbornSession, name="newbornSession"),
    path("session/family", views.familySession, name="familySession"),


    #path("sessions/", views.sessions, name="sessions"),


    path("pricing/", views.pricing, name="pricing"),
    path("profile/", views.profile, name="profile"),


    path("sign_up/", views.sign_up, name="sign_up"),
    path("logout/", views.log_out, name="logout"),


    path("control_panel/", views.control_panel, name="control_panel"),
    path("control_panel/create_session/", views.create_session, name="create_session"),
    path("control_panel/view_sessions/", views.view_sessions, name="view_sessions"),
    path("control_panel/delete_sessions/", views.delete_sessions, name="delete_sessions"),
    path("control_panel/delete_session/<str:name>", views.delete_session, name="delete_session"),

    path("control_panel/photos_sessions/", views.photos_sessions, name="photos_sessions"),




    path('session/<str:name>/', views.view_session, name='view_session'),
    path('update_photo_select/<int:photo_id>/', views.update_photo_select, name='update_photo_select'),
    path('update_photo_select_multiple/', views.update_photo_select_multiple, name='update_photo_select_multiple'),

    path('download_to_zip/<str:name>/', views.download_photos_zip, name='download_photos_zip'),
    path('download_to_file/<str:name>/', views.download_photos_folder, name='download_photos_folder'),



    path('', include("django.contrib.auth.urls")),
]

photosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

class Session(models.Model):
    name = models.CharField(max_length=100, unique=True) 
    password = models.CharField(max_length=100, default="password")

    def __str__(self):
        return self.name

from PIL import Image
import os

class Photo(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='photos/')
    session = models.ForeignKey(Session, on_delete=models.CASCADE,null=True)
    selected_to_edit = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to='thumbnails/', blank=True, null=True)
    thumbnail_medium = models.ImageField(upload_to='thumbnails_medium/', blank=True, null=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        if not self.thumbnail:
            image = Image.open(self.image.path)
            thumbnail_size = (100, 100)
            image.thumbnail(thumbnail_size)

            thumbnail_directory = "media/thumbnails/"
            os.makedirs(thumbnail_directory, exist_ok=True)

            thumbnail_path = f"{thumbnail_directory}{self.image.name.split('/')[-1]}"
            image.save(thumbnail_path)
            self.thumbnail = f"thumbnails/{self.image.name.split('/')[-1]}"
            super().save(*args, **kwargs)

        if not self.thumbnail_medium:
            image = Image.open(self.image.path)
            image.thumbnail((image.width // 7, image.height // 7))

            medium_thumbnail_directory = "media/thumbnails_medium/"
            os.makedirs(medium_thumbnail_directory, exist_ok=True)

            thumbnail_path = f"{medium_thumbnail_directory}{self.image.name.split('/')[-1]}"
            image.save(thumbnail_path)
            self.thumbnail_medium = f"thumbnails_medium/{self.image.name.split('/')[-1]}"
            super().save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        if self.thumbnail:
            if os.path.isfile(self.thumbnail.path):
                os.remove(self.thumbnail.path)

        if self.thumbnail_medium:
            if os.path.isfile(self.thumbnail_medium.path):
                os.remove(self.thumbnail_medium.path)

        super().delete(*args, **kwargs)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Session
from .models import Photo
from django.core.exceptions import ValidationError
from PIL import Image


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = None
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
        

class SessionForm(forms.ModelForm):
    class Meta:
        model = Session
        fields = ['name', 'password']


class PrivateSessionForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['title', 'image', 'session']
        widgets = {
            'image': forms.ClearableFileInput(attrs={"allow_multiple_selected": True}),
        }

    #def clean_image(self):
    #    image = self.cleaned_data.get('image')

    #    if image:
    #        if not image.name.endswith('.jpg') and not image.name.endswith('.jpeg') and not image.name.endswith('.JPG'):
    #            raise ValidationError('Picture need to be in JPEG.')
    #        try:
    #            img = Image.open(image)
    #            if img.format.lower() != 'jpeg':
    #                raise ValidationError('This is not JPEG.')
    #        except Exception as e:
    #            raise ValidationError('Cannot open file as JPEG.')

    #    return image

main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from .forms import SignupForm
from .forms import SessionForm
from .models import Session
from .forms import PrivateSessionForm
from .forms import PhotoForm
from .models import Photo
import os
from django.conf import settings
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO
from django.core.files import File
from django.core.exceptions import ValidationError
from django.http import JsonResponse
import json
import io
import pyzipper




def index(request):
    context = {}
    return render(request, 'main/base.html', context)

def home(request):
    context = {}
    return render(request, 'main/home.html', context)

def portfolio(request):
    context = {}
    return render(request, 'main/portfolio.html', context)

def pricing(request):
    context = {}
    return render(request, 'main/pricing.html', context)

def weddingSession(request):
    context = {}
    return render(request, 'main/session/wedding.html', context)
def newbornSession(request):
    context = {}
    return render(request, 'main/session/newborn.html', context)
def familySession(request):
    context = {}
    return render(request, 'main/session/family.html', context)

def profile(request):
    context = {}
    return render(request, 'main/profile.html', context)

def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else: form = SignupForm()
    context = {'form':form}
    return render(request, 'registration/sign_up.html', context)

def log_out(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/home')
    context = {}
    return render(request, 'registration/logout.html', context)



@user_passes_test(lambda user: user.is_superuser)
def control_panel(request):
    context = {}
    return render(request, 'main/control_panel/control_panel.html', context)

@user_passes_test(lambda user: user.is_superuser)
def create_session(request):
    if request.method == 'POST':
        name = request.POST['name']
        form = SessionForm(request.POST)
        if form.is_valid():
            session = form.save()
            return redirect('view_session', name=name)
    else: form = SessionForm()
    context = {'form':form}
    return render(request, 'main/control_panel/create_session.html', context)




@user_passes_test(lambda user: user.is_superuser)
def delete_sessions(request):
    sessions = Session.objects.all()
    context = {'sessions': sessions}
    return render(request, 'main/control_panel/delete_sessions.html', context)

@user_passes_test(lambda user: user.is_superuser)
def delete_session(request,name):
    session = Session.objects.filter(name=name).delete()
    context = {'session': session}
    return render(request, 'main/session/session_template.html', context)


@user_passes_test(lambda user: user.is_superuser)
def view_sessions(request):
    sessions = Session.objects.all()

    for session in sessions:
        photos = session.photo_set.all()
        photos_size = []
        for photo in photos:
            photos_size.append(photo.image.size / (1024*1024))
        photos_size_in_session = round(sum(photos_size))
        session.photos_size_in_session = photos_size_in_session
    context = {'sessions': sessions}
    return render(request, 'main/control_panel/view_sessions.html', context)


def view_session(request, name):
    session = get_object_or_404(Session, name=name)
    photos = session.photo_set.all()
    photos_size = []
    context = {}
    for photo in photos:
        photos_size.append(photo.image.size/(1024*1024))
    photos_size_in_session = round(sum(photos_size))

    if request.user.is_superuser:
        context = {'session': session, 'photos':photos, 'photos_size_in_session':photos_size_in_session}
        return render(request, 'main/session/private_session.html', context)

    if request.method == 'POST':
        form = PrivateSessionForm(request.POST)
        if form.is_valid():
            entered_password = form.cleaned_data['password']
            if entered_password == session.password:
                context = {'session': session, 'photos':photos}
                return render(request, 'main/session/private_session.html', context)
    
    else:
        form = PrivateSessionForm()
    
    context = {'form': form}
    return render(request, 'main/session/private_session_form.html', context)


@user_passes_test(lambda user: user.is_superuser)
def photos_sessions(request):
    context = {}
    sessions = Session.objects.all()

    if request.method == 'POST':
        if 'clear_session' in request.POST:
            session_id =  request.POST['session']
            dropped_photo = Photo.objects.filter(session_id=session_id)
            for photo in dropped_photo:
                photo.delete()


        if 'delete_session' in request.POST:
            session_id =  request.POST['session']
            dropped_photo = Photo.objects.filter(session_id=session_id)
            for photo in dropped_photo:
                photo.delete()
                
            Session.objects.filter(id=session_id).delete()


        if 'add_images_session' in request.POST:
            form = PhotoForm(request.POST, request.FILES)
            if form.is_valid():
                images = request.FILES.getlist('image')
                image_type = request.POST.get('image_type')
                uploaded_photos = []

                for image in images:
                    uploaded_photos.append('a')
                    print(uploaded_photos)
                    try:
                        img = Image.open(image)
                        if img.format !='JPEG':
                            raise ValidationError("not jpeg")
                        
                        if image_type == 'original':
                            photo = Photo(title=image.name, image=image, session=form.cleaned_data['session'])
                            photo.save()

                        elif image_type == 'resized':
                            create_watermarked_photo(image, form.cleaned_data['session'], request.POST['watermark_opacity'])

                    except Exception as e:
                        form.add_error('image',str(e))

                img_obj = form.instance
                context = {'form': form, 'img_obj': img_obj, 'sessions':sessions,  'uploaded_photos': uploaded_photos}
                return render(request, 'main/control_panel/photos_sessions.html', context)
    else:
        form = PhotoForm()

    photos = Photo.objects.all()
    context = {'sessions': sessions, 'photos': photos}
    return render(request, 'main/control_panel/photos_sessions.html', context)


def update_photo_select(request, photo_id):
    if request.method == 'POST':
        photo = get_object_or_404(Photo, id=photo_id)
        photo.selected_to_edit = not photo.selected_to_edit
        photo.save()
        return JsonResponse({'status': 'ok'})
    

def download_photos_zip(request, name):
    session = get_object_or_404(Session, name=name)
    photos = session.photo_set.all()
    zip_buffer = io.BytesIO()
    password = f"{session.password}"

    with pyzipper.AESZipFile(zip_buffer, 'w', compression=pyzipper.ZIP_LZMA, encryption=pyzipper.WZ_AES) as zip_file:
        zip_file.setpassword(password.encode())
        for photo in photos:
            zip_file.write(photo.image.path, arcname=photo.image.name)
    zip_buffer.seek(0)
    response = HttpResponse(zip_buffer.read(), content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename={}'.format(f"{name}_photos.zip")
    return response


import zipfile
def download_photos_folder(request, name):
    session = get_object_or_404(Session, name=name)
    photos = session.photo_set.all()
    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, 'w') as zip_file:
        for photo in photos:
            with open(photo.image.path, 'rb') as photo_file:
                zip_file.writestr(photo.image.name, photo_file.read())

    response = HttpResponse(zip_buffer.getvalue(), content_type='application/zip')
    response['Content-Disposition'] = f'attachment; filename={name}_photos.zip'

    return response





def update_photo_select_multiple(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            photo_ids = data.get('photoIds', [])

            for photo_id in photo_ids:
                photo = get_object_or_404(Photo, id=photo_id)
                photo.selected_to_edit = False
                photo.save()
            return JsonResponse({'message': 'Photos updated successfully'})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    return JsonResponse({'message': 'Method not allowed'}, status=405)


def create_watermarked_photo(image, session, watermark_opacity):
    img = Image.open(image)
    img.thumbnail((img.width, img.height))
    text = "moccastudio"
    opacity = int(watermark_opacity)
    grid = 5

    img_width, img_height = img.size
    text_size = img_width // 32
    font = ImageFont.truetype("arial.ttf", text_size)
    text_color = (255, 255, 255, opacity)

    cell_width = img_width // grid
    cell_height = img_height // grid
    for i in range(grid**2):
        row = i // grid
        col = i % grid
        x = col * cell_width + cell_width // 2 - cell_width // 3
        y = row * cell_height + cell_height // 2 

        text_image = Image.new('RGBA', (cell_width, cell_height), (255, 255, 255, 0))
        text_draw = ImageDraw.Draw(text_image)

main/templates/main/control_panel/control_panel.html
{% extends 'main/base.html' %}
{% block title %}
    Control panel
{% endblock %}



{% block content %}
{% if user.is_superuser %}
<style>
    .card{
        margin-top:20px;
        margin-bottom:20px;
    }
</style>

    <div class="row px-5 pt-2 text-center">
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Create sessions</h5>
              <p class="card-text">Create a new session for user</p>
              <a href="create_session" class="btn btn-primary">Create sessions</a>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Read sessions</h5>
              <p class="card-text">View session as user see it</p>
              <a href="view_sessions" class="btn btn-primary">Read sessions</a>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Update sessions</h5>
                <p class="card-text">Update existing session</p>
                <a href="#" class="btn btn-primary">Update sessions</a>
              </div>
            </div>
          </div>

          <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Delete sessions</h5>
                <p class="card-text">Delete existing session</p>
                <a href="delete_sessions" class="btn btn-primary">Delete sessions</a>
              </div>
            </div>
          </div>

          <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Manage photos</h5>
                <p class="card-text">Manage photos overall</p>
                <a href="photos_sessions" class="btn btn-primary">Manage photos</a>
              </div>
            </div>
          </div>

          <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">View user panel</h5>
                <p class="card-text">Check user activity and others</p>
                <a href="#" class="btn btn-primary">View user panel</a>
              </div>
            </div>
          </div>

    </div>
{% endif %}
{% endblock %}

main/templates/main/control_panel/create_session.html
{% extends 'main/base.html' %}
{% block title %}
    Create session
{% endblock %}



{% block content %}
{% if user.is_superuser %}
    <div>Create session</div>  
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create session</button>
        <button type="button" id="generate-password-button">Generate Password</button>

    </form>
{% endif %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const generatePasswordButton = document.getElementById("generate-password-button");
        generatePasswordButton.addEventListener("click", function() {
            const passwordField = document.getElementById("id_password");
            passwordField.value = generateRandomPassword();
        });
    
        function generateRandomPassword() {
            const characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            let password = "";
            for (let i = 0; i < 12; i++) {
                const randomIndex = Math.floor(Math.random() * characters.length);
                password += characters.charAt(randomIndex);
            }
            return password;
        }
    });
</script>
{% endblock %}

main/templates/main/control_panel/delete_sessions.html
{% extends 'main/base.html' %}
{% block title %}
    View session
{% endblock %}



{% block content %}
{% if user.is_superuser %}
    <div>View session</div>  

    {% for session in sessions %}
    <form method="POST" action="{% url 'delete_session' session.name %}">
        {% csrf_token %}
        <input type="hidden" name="session_name" value="{{ session.name }}">
        <p>{{ session.name }} <input type="submit" value="Usuń {{session.name}}"></p>
    </form>
    {% endfor %}

{% endif %}
{% endblock %}

main/templates/main/control_panel/photos_sessions.html
{% extends 'main/base.html' %}
{% block title %}
    Photos session
{% endblock %}



{% block content %}
{% if user.is_superuser %}
<div class="m-3">
    <div class="row">
        <div class="col-sm-4">
            <div class="card" style="height: 24rem;">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                    <h5 class="card-title">Add images</h5>
                    <p class="card-text">
                        <label for="id_image_type">Image Type:</label><br>
                        <input type="radio" name="image_type" id="id_image_type_original" value="original" checked>
                        <label for="id_image_type_original">Original</label><br>
                        <input type="radio" name="image_type" id="id_image_type_resized" value="resized">
                        <label for="id_image_type_resized">Resized</label>
                        <label for="watermark_opacity">, Watermark opacity:</label>
                        <input type="range" name="watermark_opacity" id="watermark_opacity" min="0" max="100" value="50" step="10">

                    </p>
                    <p class="card-text">
                        <label for="id_title">Title:</label>
                        <input type="text" name="title" id="id_title" value="title">
                    </p>
                    <p class="card-text">
                        <label for="id_image">Image:</label>
                        <input type="file" name="image" id="id_image" multiple>
                    </p>
                    <p class="card-text">
                        <label for="id_session">Session:</label>
                        <select name="session" id="id_session">
                            {% for session in sessions %}
                                <option value="{{ session.id }}">{{ session.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p class="card-text">
                        <input type="submit" name="add_images_session" value="Add image">
                    </p>
                    <p class="card-text">
                        {% if img_obj %}  <h3>Succesfully uploaded : {{img_obj.title}}</h3>     {% endif %}
                    </p>            
                </div>
                </form>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card" style="height: 24rem;">
                <form method="post">
                    {% csrf_token %}
                    <div class="card-body">
                    <h5 class="card-title">Clear image from session</h5>
                    <p class="card-text">
                        <label for="id_session">Session:</label>
                        <select name="session" id="id_session">
                            {% for session in sessions %}
                                <option value="{{ session.id }}">{{ session.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p class="card-text">
                        <input type="submit" name="clear_session" value="Delete all images from session">
                    </p>
                </div>
                </form>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card" style="height: 24rem;">
                <form method="post">
                    {% csrf_token %}
                    <div class="card-body">
                    <h5 class="card-title">Delete entire session</h5>
                    <p class="card-text">
                        <label for="id_session">Session:</label>
                        <select name="session" id="id_session">
                            {% for session in sessions %}
                                <option value="{{ session.id }}">{{ session.name }}</option>
                            {% endfor %}
                        </select>
                    </p>
                    <p class="card-text">
                        <input type="submit" name="delete_session" value="Delete session">
                    </p> 
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="m-3">
    <div class="card text-center">Sessions</div>
    {% for session in sessions %}
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h5 class="card-title">{{ session.name }}</h5>
                            <p class="card-text">
                                {% for photo in session.photo_set.all %}
                                    {% if forloop.counter <= 9 %}
                                        <img src="{{ photo.thumbnail.url }}" alt="connect" style="max-height: 100px">
                                    {% elif forloop.counter == 10 %}
                                        <span>+{{ session.photo_set.all.count|add:"-9" }} ...</span>
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </div>
                        <div class="col-md-3 text-center">
                            <a href="/session/{{session.name}}"><button class="btn btn-primary">Preview</button></a>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="session" value="{{ session.id }}">
                                <button type="submit" name="clear_session" class="btn btn-warning">Clear</button>
                            </form>

                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="session" value="{{ session.id }}">
                                <button type="submit" name="delete_session" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    {% endfor %}
</div>






{% endif %}
{% endblock %}

main/templates/main/control_panel/view_sessions.html
{% extends 'main/base.html' %}
{% block title %}
    View session
{% endblock %}



{% block content %}
{% if user.is_superuser %}
<div class="m-3">
    <div class="card text-center">Sessions</div>
    {% for session in sessions %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <h5 class="card-title">Name: <a href="{% url 'view_session' session.name %}">{{ session.name }}</a> </h5>
                        <h5 class="card-title">Password: {{ session.password }}</h5>
                        <h5 class="card-title">Number of photos in sessions {{ session.photo_set.all.count }}</h5>
                        <h5 class="card-title">Size of all photos in this session {{session.photos_size_in_session}} MB</h5>
                        <p class="card-text">
                            {% for photo in session.photo_set.all %}
                                {% if forloop.counter <= 9 %}
                                    <img src="{{ photo.thumbnail.url }}" alt="connect" style="max-height: 100px">
                                {% elif forloop.counter == 10 %}
                                    <span>+{{ session.photo_set.all.count|add:"-9" }} ...</span>
                                {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}